config/routes.rb
Rails.application.routes.draw do
  get 'product/new'
  get 'restaurants/new'
  get 'admin/index'
  get 'home/index'
  root 'home#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'cart', to: 'cart_items#index'

  get '/admin', to: 'admin#index'
  get '/admin/restaurants/new', to: 'restaurants#new'

  resources :users, only: [:create]
  resources :restaurants

  get 'restaurants/delete/:id', to: 'restaurants#destroy', as: 'restaurant_destroy'
  
  resources :restaurants do
    resources :products
  end

  resources :products, only: [:create, :destroy]

  resources :cart_items, only: [:create, :destroy] do
    patch :update_quantity, on: :member
  end

  resources :orders, only: [:create, :index]

  resources :orders do
    member do
      patch :mark_in_progress
      patch :mark_done
      patch :mark_canceled
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :user
  
  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products
  
  def total_price
    order_products.sum { |order_product| order_product.quantity * order_product.product.price }
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :restaurant
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
end

app/models/restaurant.rb
require 'mini_magick'

class Restaurant < ApplicationRecord
  has_many :products, dependent: :destroy
  has_one_attached :image

  after_save :crop_image

  def crop_image
    # return unless image.attached?
    # image.variant(resize_to_fill: [500, 350]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :phone, presence: true
  has_many :orders
  validates :email, uniqueness: true
  validates :phone, uniqueness: true
  
  def cart_items
    CartItem.where(user_id: id)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def index
    @restaurants = Restaurant.all
  end

  private

  def require_admin
    unless current_user && current_user.is_admin?
      flash[:danger] = 'У вас нет прав для просмотра этой страницы'
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.status = 'created'
    @order.date = Time.now

    @cart_items = current_user.cart_items
    @cart_items.each do |cart_item|
      @order.order_products.build(product_id: cart_item.product_id, quantity: cart_item.quantity)
    end

    puts '========'
    puts @order

    @order.save
    puts @order.errors.full_messages


    current_user.cart_items.destroy_all
    redirect_to root_path
  end

  def index
    @orders = Order.order(id: :desc)
  end

  def mark_in_progress
    @order = Order.find(params[:id])
    @order.update(status: "in_progress")
    redirect_to orders_path
  end

  def mark_done
    @order = Order.find(params[:id])
    @order.update(status: "done")
    redirect_to orders_path
  end

  def mark_canceled
    @order = Order.find(params[:id])
    @order.update(status: "canceled")
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.password.blank?
      flash.now[:alert] = "Пароль не може бути порожнім."
      render :new
      return
    end

    if @user.password_confirmation.blank?
      flash.now[:alert] = "Пароль не може бути порожнім."
      render :new
      return
    end

    if @user.password_confirmation != @user.password
      flash.now[:alert] = "Паролі не співпадають."
      render :new
      return
    end

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      if @user.errors[:email].any? # Проверка ошибок валидации email
        flash.now[:alert] = "Реєстрацію за цією почтой вже здійснено."
      elsif @user.errors[:phone].any? # Проверка ошибок валидации phone
        flash.now[:alert] = "Реєстрацію за цим телефоном вже здійснено."
      else
        flash.now[:alert] = "Не вдалось зареєструватися."
      end
      render :new
    end
  end

  private

  def user_params
    params.permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Административная панель</h1>
<p>Это страница только для администраторов.</p>

<h1>Restaurants</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |r| %>
      <tr>
        <td><%= r.name %></td>
        <td><%= r.address %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= button_tag class: 'btn btn-primary' do %>
  <%= link_to 'Добавить', admin_restaurants_new_path %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title><%= content_for?(:html_title) ? yield(:html_title) : "Default" %></title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <% if current_user %>

    <header data-bs-theme="dark">
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <a href="/" class="navbar-brand d-flex align-items-center">
            <strong>Food Delivery</strong>
          </a>
          <div>
            <% if current_user.is_admin %>
              <%= link_to "Замовлення", orders_path, class: "btn btn-outline-light" %>
            <% end %>
            <%= link_to "Кошик", cart_path, class: "btn btn-outline-light" %>
            <%= link_to "Вийти", logout_path, class: "btn btn-outline-light" %>
          </div>
        </div>
      </div>
    </header>

    <% end %>

    <%= yield %>

    <% if current_user %>

    <footer class="container py-5">
      <div class="row">
        <div class="col-12 col-md">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
          <small class="d-block mb-3 text-body-secondary">&copy; 2017–2023</small>
        </div>
        <div class="col-6 col-md">
          <h5>Корисні посилання</h5>
          <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Про нас</a></li>
            <li><a class="link-secondary" href="#">Часті запитання</a></li>
            <li><a class="link-secondary" href="#">Блог</a></li>
            <li><a class="link-secondary" href="#">Контакти</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Соц. мережі</h5>
          <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Facebook</a></li>
            <li><a class="link-secondary" href="#">Twitter</a></li>
            <li><a class="link-secondary" href="#">Instagram</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Співпраця</h5>
          <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Вакансії</a></li>
            <li><a class="link-secondary" href="#">Кур'єри</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Інше</h5>
          <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Правила й умови</a></li>
            <li><a class="link-secondary" href="#">Політика конфіденційності</a></li>
            <li><a class="link-secondary" href="#">Політика файлів cookie</a></li>
          </ul>
        </div>
      </div>
    </footer>

    <% end %>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>