config/routes.rb
Rails.application.routes.draw do
  get 'product/new'
  get 'restaurants/new'
  get 'admin/index'
  get 'home/index'
  root 'home#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'cart', to: 'cart_items#index'

  get '/admin', to: 'admin#index'
  get '/admin/restaurants/new', to: 'restaurants#new'

  resources :users, only: [:create]
  resources :restaurants

  get 'restaurants/delete/:id', to: 'restaurants#destroy', as: 'restaurant_destroy'
  
  resources :restaurants do
    resources :products
  end

  resources :products, only: [:create, :destroy]

  resources :cart_items, only: [:create, :destroy] do
    patch :update_quantity, on: :member
  end

  resources :orders, only: [:create, :index]

  resources :orders do
    member do
      patch :mark_in_progress
      patch :mark_done
      patch :mark_canceled
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :user
  
  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products
  
  def total_price
    order_products.sum { |order_product| order_product.quantity * order_product.product.price }
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :restaurant
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
end

app/models/restaurant.rb
require 'mini_magick'

class Restaurant < ApplicationRecord
  has_many :products, dependent: :destroy
  has_one_attached :image

  after_save :crop_image

  def crop_image
    # return unless image.attached?
    # image.variant(resize_to_fill: [500, 350]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :phone, presence: true
  has_many :orders
  validates :email, uniqueness: true
  validates :phone, uniqueness: true
  
  def cart_items
    CartItem.where(user_id: id)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def index
    @restaurants = Restaurant.all
  end

  private

  def require_admin
    unless current_user && current_user.is_admin?
      flash[:danger] = 'У вас нет прав для просмотра этой страницы'
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.status = 'created'
    @order.date = Time.now

    @cart_items = current_user.cart_items
    @cart_items.each do |cart_item|
      @order.order_products.build(product_id: cart_item.product_id, quantity: cart_item.quantity)
    end

    puts '========'
    puts @order

    @order.save
    puts @order.errors.full_messages


    current_user.cart_items.destroy_all
    redirect_to root_path
  end

  def index
    @orders = Order.order(id: :desc)
  end

  def mark_in_progress
    @order = Order.find(params[:id])
    @order.update(status: "in_progress")
    redirect_to orders_path
  end

  def mark_done
    @order = Order.find(params[:id])
    @order.update(status: "done")
    redirect_to orders_path
  end

  def mark_canceled
    @order = Order.find(params[:id])
    @order.update(status: "canceled")
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user
  
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.build
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.build(product_params)
  
    if @product.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  
    if @product.update(product_params)
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Неправильний емейл або пароль."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.password.blank?
      flash.now[:alert] = "Пароль не може бути порожнім."
      render :new
      return
    end

    if @user.password_confirmation.blank?
      flash.now[:alert] = "Пароль не може бути порожнім."
      render :new
      return
    end

    if @user.password_confirmation != @user.password
      flash.now[:alert] = "Паролі не співпадають."
      render :new
      return
    end

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      if @user.errors[:email].any? # Проверка ошибок валидации email
        flash.now[:alert] = "Реєстрацію за цією почтой вже здійснено."
      elsif @user.errors[:phone].any? # Проверка ошибок валидации phone
        flash.now[:alert] = "Реєстрацію за цим телефоном вже здійснено."
      else
        flash.now[:alert] = "Не вдалось зареєструватися."
      end
      render :new
    end
  end

  private

  def user_params
    params.permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% content_for(:html_title) { 'Головна' } %>

  <% if current_user %>
  <div class="container">
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Food Delivery</h1>
          <p class="lead text-body-secondary">Lorem Ipsum - це текст-"риба", що використовується в друкарстві та дизайні. Lorem Ipsum є, фактично, стандартною "рибою" аж з XVI сторіччя, коли невідомий друкар взяв шрифтову гранку та склав на ній підбірку зразків шрифтів.</p>
          <!-- <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
          </p> -->
        </div>
      </div>
    </section>  
    </div>
    <div class="album py-5 bg-body-tertiary">
    <div class="container">
    <div class="text-center">
      <h3>Ресторани</h3>
      <% if current_user.is_admin %>
        <%= link_to 'Додати новий', new_restaurant_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
    <br><br>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
      <% @restaurants.each do |restaurant| %>
        <div class="col">
          <div class="card shadow-sm">
            <% if restaurant.image.attached? %> 
              <%= image_tag restaurant.image.variant(resize_to_fill: [500, 350]).processed, class: 'card-img-top' %>
            <% end %>
            <div class="card-body">
              <h5><%= restaurant.name %></h5>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Товари', restaurant_path(restaurant), class: 'btn btn-sm btn-outline-primary' %>
                  <% if current_user.is_admin %>
                    <%= link_to 'Редагувати', edit_restaurant_path(restaurant), class: 'btn btn-sm btn-primary' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
      </div>
      <br>
    </div>
  <% else %>
    <header class="site-header py-1">
      <h1 style="text-align: center;">Food Delivery</h1>
    </header>

    <main>
      <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary intro-banner" style="background-image: url(<%= asset_path('banner.jpg') %>
      )">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
          <h3 class="display-5">Fast Food Delivery</h3>
          <p class="lead fw-normal">Спробуй зараз</p>
          <%= link_to "Увійти", login_path, class: "btn btn-outline-light" %>
          <%= link_to "Зареєструватися", signup_path, class: "btn btn-outline-light" %>
        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
      </div>
      <div class="container">
        <div class="about-us">
          <h3>Про нас</h3>
          <p>Lorem Ipsum - це текст-"риба", що використовується в друкарстві та дизайні. Lorem Ipsum є, фактично, стандартною "рибою" аж з XVI сторіччя, коли невідомий друкар взяв шрифтову гранку та склав на ній підбірку зразків шрифтів. "Риба" не тільки успішно пережила п'ять століть, але й прижилася в електронному верстуванні, залишаючись по суті незмінною. Вона популяризувалась в 60-их роках минулого сторіччя завдяки виданню зразків шрифтів Letraset, які містили уривки з Lorem Ipsum, і вдруге - нещодавно завдяки програмам комп'ютерного верстування на кшталт Aldus Pagemaker, які використовували різні версії Lorem Ipsum.</p>
        </div>
      </div>
    </main>

    <footer class="container py-5">
      <div class="row">
        <div class="col-12 col-md">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
          <small class="d-block mb-3 text-body-secondary">&copy; 2017–2023</small>
        </div>
        <div class="col-6 col-md">
          <h5>Корисні посилання</h5>
          <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Про нас</a></li>
            <li><a class="link-secondary" href="#">Часті запитання</a></li>
            <li><a class="link-secondary" href="#">Блог</a></li>
            <li><a class="link-secondary" href="#">Контакти</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Соц. мережі</h5>
          <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Facebook</a></li>
            <li><a class="link-secondary" href="#">Twitter</a></li>
            <li><a class="link-secondary" href="#">Instagram</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Співпраця</h5>
          <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Вакансії</a></li>
            <li><a class="link-secondary" href="#">Кур'єри</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Інше</h5>
          <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Правила й умови</a></li>
            <li><a class="link-secondary" href="#">Політика конфіденційності</a></li>
            <li><a class="link-secondary" href="#">Політика файлів cookie</a></li>
          </ul>
        </div>
      </div>
    </footer>
  <% end %>