config/routes.rb
Rails.application.routes.draw do
  get 'product/new'
  get 'restaurants/new'
  get 'admin/index'
  get 'home/index'
  root 'home#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'cart', to: 'cart_items#index'

  get '/admin', to: 'admin#index'
  get '/admin/restaurants/new', to: 'restaurants#new'

  resources :users, only: [:create]
  resources :restaurants

  get 'restaurants/delete/:id', to: 'restaurants#destroy', as: 'restaurant_destroy'
  
  resources :restaurants do
    resources :products
  end

  resources :products, only: [:create, :destroy]

  resources :cart_items, only: [:create, :destroy] do
    patch :update_quantity, on: :member
  end

  resources :orders, only: [:create, :index]

  resources :orders do
    member do
      patch :mark_in_progress
      patch :mark_done
      patch :mark_canceled
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :user
  
  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products
  
  def total_price
    order_products.sum { |order_product| order_product.quantity * order_product.product.price }
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :restaurant
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
end

app/models/restaurant.rb
require 'mini_magick'

class Restaurant < ApplicationRecord
  has_many :products, dependent: :destroy
  has_one_attached :image

  after_save :crop_image

  def crop_image
    # return unless image.attached?
    # image.variant(resize_to_fill: [500, 350]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :phone, presence: true
  has_many :orders
  validates :email, uniqueness: true
  validates :phone, uniqueness: true
  
  def cart_items
    CartItem.where(user_id: id)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def index
    @restaurants = Restaurant.all
  end

  private

  def require_admin
    unless current_user && current_user.is_admin?
      flash[:danger] = 'У вас нет прав для просмотра этой страницы'
      redirect_to root_path
    end
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :logged_in_user
  
  def create
    @cart_item = current_user.cart_items.find_by(product_id: params[:product_id])

    if @cart_item.present?
      @cart_item.update(quantity: @cart_item.quantity + params[:quantity].to_i)
    else
      @product = Product.find(params[:product_id])
      @cart_item = current_user.cart_items.build(product: @product, quantity: params[:quantity])
    end

    if @cart_item.save
      render json: { success: true }
    else
      render json: { success: false }
    end
  end

  def update_quantity
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(quantity: params[:quantity])
    render json: { success: false }
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    render json: { success: true }
  end

  def index
    @cart_items = current_user.cart_items
    @order = Order.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.status = 'created'
    @order.date = Time.now

    @cart_items = current_user.cart_items
    @cart_items.each do |cart_item|
      @order.order_products.build(product_id: cart_item.product_id, quantity: cart_item.quantity)
    end

    puts '========'
    puts @order

    @order.save
    puts @order.errors.full_messages


    current_user.cart_items.destroy_all
    redirect_to root_path
  end

  def index
    @orders = Order.order(id: :desc)
  end

  def mark_in_progress
    @order = Order.find(params[:id])
    @order.update(status: "in_progress")
    redirect_to orders_path
  end

  def mark_done
    @order = Order.find(params[:id])
    @order.update(status: "done")
    redirect_to orders_path
  end

  def mark_canceled
    @order = Order.find(params[:id])
    @order.update(status: "canceled")
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user
  
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.build
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.build(product_params)
  
    if @product.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  
    if @product.update(product_params)
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Неправильний емейл або пароль."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.password.blank?
      flash.now[:alert] = "Пароль не може бути порожнім."
      render :new
      return
    end

    if @user.password_confirmation.blank?
      flash.now[:alert] = "Пароль не може бути порожнім."
      render :new
      return
    end

    if @user.password_confirmation != @user.password
      flash.now[:alert] = "Паролі не співпадають."
      render :new
      return
    end

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      if @user.errors[:email].any? # Проверка ошибок валидации email
        flash.now[:alert] = "Реєстрацію за цією почтой вже здійснено."
      elsif @user.errors[:phone].any? # Проверка ошибок валидации phone
        flash.now[:alert] = "Реєстрацію за цим телефоном вже здійснено."
      else
        flash.now[:alert] = "Не вдалось зареєструватися."
      end
      render :new
    end
  end

  private

  def user_params
    params.permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/index.html.erb
<% content_for(:html_title) { 'Кошик' } %>


<div class="container">
  <h1>Товари в кошику</h1><br>

  <% if @cart_items.empty? %>
    <p>Ваш кошик порожній.</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Товар</th>
          <th>Ціна товара</th>
          <th>Ресторан</th>
          <th>Кількість</th>
          <th>Загальна ціна</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |cart_item| %>
          <tr>
            <td><%= cart_item.product.name %></td>
            <td>₴ <%= cart_item.product.price %></td>
            <td><%= cart_item.product.restaurant.name %></td>
            <td>
              <div class="input-group input-quantity">
                <div class="input-group-prepend">
                  <button class="btn btn-outline-secondary btn-first decrease-quantity" type="button" data-id="<%= cart_item.id %>">-</button>
                </div>
                <%= number_field_tag :quantity, 1, min: 1, max: 10, id: 'number-input', class: 'form-control', value: cart_item.quantity %>
                <div class="input-group-append">
                  <button class="btn btn-outline-secondary btn-second increase-quantity" type="button" data-id="<%= cart_item.id %>">+</button>
                </div>
              </div>
            </td>
            <td>₴ <%= cart_item.total_price %></td>
            <td><button class="btn btn-danger delete-from-cart" data-id="<%= cart_item.id %>">Видалити</button></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br><hr>

    <div class="order">
      <h3>Оформити замовлення</h3>
      <%= form_with(model: @order, url: orders_path) do |form| %>
        <div class="form-group mb-3">
          <%= form.label :address, "Адреса", class: 'form-label' %>
          <%= form.text_field :address, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.submit "Оформити", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/orders/index.html.erb
<% content_for(:html_title) { 'Замовлення' } %>

<div class="container">

  <h2>Список замовлень</h2>
  <br>

  <table class="table">
    <thead>
      <tr>
        <th>Товари</th>
        <th>Покупець</th>
        <th>Телефон</th>
        <th>Адреса</th>
        <th>Загальна ціна</th>
        <th>Статус</th>
        <th>Дата</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <table class="table">
              <thead>
                <tr>
                  <th>Назва товару</th>
                  <th>Ресторан</th>
                  <th>Кількість</th>
                  <th>Загальна ціна</th>
                </tr>
              </thead>
              <tbody>
                <% order.order_products.each do |order_product| %>
                  <tr>
                    <td><%= order_product.product.name %></td>
                    <td><%= order_product.product.restaurant.name %></td>
                    <td><%= order_product.quantity %></td>
                    <td>₴ <%= order_product.quantity * order_product.product.price %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </td>
          <td><%= order.user.name %></td>
          <td><%= order.user.phone %></td>
          <td><%= order.address %></td>
          <td>₴ <%= order.total_price %></td>
          <td>
            <% if order.status == 'created' %>
              Новий
            <% elsif order.status == 'done' %>
              Виконано
            <% elsif order.status == 'canceled' %>
              Скасовано
            <% else %>
              В процесі
            <% end %>
          </td>
          <td><%= order.date %></td>
          <% if order.status == 'created' %>
            <td>
              <%= link_to "Прийняти", mark_in_progress_order_path(order), method: :patch %>
            </td>
            <td>
              <%= link_to "Відмінити", mark_canceled_order_path(order), method: :patch %>
            </td>
          <% elsif order.status == 'in_progress' %>
            <td>
              <%= link_to "Виконано", mark_done_order_path(order), method: :patch %>
            </td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/products/edit.html.erb
<% content_for(:html_title) { 'Редагувати продукт' } %>

<div class="container">
  <h1>Редагувати продукт</h1>
  <%= link_to "Видалити продукт", product_path(@product), method: :delete, data: { confirm: 'Ви впевнені, що хочете видалити цей продукт?' }, class: "btn btn-danger" %><br><br>
  <%= form_with(model: [@restaurant, @product], local: true) do |p| %>
    <div class="mb-3">
      <%= p.label 'Назва', class: 'form-label' %>
      <%= p.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= p.label 'Картинка' %>
      <%= p.file_field :image %>
    </div>
    
    <div class="mb-3">
      <%= p.label 'Ціна', class: 'form-label' %>
      <%= p.text_field :price, class: 'form-control' %>
    </div>
  
    <div class="mb-3">
      <%= p.label 'Опис', class: 'form-label' %>
      <%= p.text_area :description, class: 'form-control' %>
    </div>
  
    <%= p.submit "Зберегти", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/products/new.html.erb
<% content_for(:html_title) { 'Добавити продукт' } %>

<div class="container">
  <h1>Створити новий продукт</h1>
  <%= form_with(model: [@restaurant, @product], local: true) do |p| %>
    <div class="mb-3">
      <%= p.label 'Назва', class: 'form-label' %>
      <%= p.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= p.label 'Картинка' %>
      <%= p.file_field :image %>
    </div>
    
    <div class="mb-3">
      <%= p.label 'Ціна', class: 'form-label' %>
      <%= p.number_field :price, class: 'form-control' %>
    </div>
  
    <div class="mb-3">
      <%= p.label 'Опис', class: 'form-label' %>
      <%= p.text_area :description, class: 'form-control' %>
    </div>
  
    <%= p.submit 'Створити', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/products/show.html.erb
<% content_for(:html_title) { @product.name } %>

<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light"><%= @restaurant.name %></h1>
        <p class="lead text-body-secondary"><%= @restaurant.description %></p>
        <p>
          <%= link_to 'Повернутися', restaurant_path(@restaurant), class: 'btn btn-primary' %>
        </p>
      </div>
    </div>
  </section>

<div class="single-product bg-body-tertiary">
  <div class="container">
    <div class="row">
      <div class="col-sm-1"></div>
      <div class="col-sm-5">
      <% if @product.image.attached? %> 
        <%= image_tag @product.image.variant(resize_to_fill: [700, 450]).processed, class: 'img-fluid' %>
      <% end %>
      </div>
      <div class="col-sm-5">
        <h3><%= @product.name %></h3>
        <p><%= @product.description %></p>
        <p class="price">₴ <%= @product.price %></p>
        <form id="add-to-cart">
          <%= hidden_field_tag :product_id, @product.id %>
          <div class="input-group input-quantity">
            <div class="input-group-prepend">
              <button class="btn btn-outline-secondary btn-first" type="button" onclick="decreaseValue()">-</button>
            </div>
            <%= number_field_tag :quantity, 1, min: 1, max: 10, id: 'number-input', class: 'form-control' %>
            <div class="input-group-append">
              <button class="btn btn-outline-secondary btn-second" type="button" onclick="increaseValue()">+</button>
            </div>
          </div>
          <br>
          <button type="submit" class="btn btn-primary">Додати в кошик</button>
          <div class="alert alert-success added-to-cart-alert" style="margin-top: 20px;" role="alert">
            Товар було успішно додано в кошик
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  function increaseValue() {
    var value = parseInt(document.getElementById('number-input').value, 10);
    value = isNaN(value) ? 0 : value;
    value++;
    if (value > 10) {
      value = 10;
    }
    document.getElementById('number-input').value = value;
  }

  function decreaseValue() {
    var value = parseInt(document.getElementById('number-input').value, 10);
    value = isNaN(value) ? 0 : value;
    value--;
    if (value < 1) {
      value = 1;
    }
    document.getElementById('number-input').value = value;
  }
</script>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% content_for(:html_title) { 'Реєстрація' } %>

<div class="form-signup">
  <%= form_with url: users_path, method: :post, data: {turbo: false} do |form| %>
    <%= csrf_meta_tags %>

    <h1 class="h3 mb-3 fw-normal">Реєстрація</h1>

    <div class="form-floating">
      <%= text_field_tag :name, @user.name, required: true, class: 'form-control', id: 'floatingInput', placeholder: 'Ім\'я' %>
      <label for="floatingInput">Ім'я</label>
    </div>
    <div class="form-floating">
      <%= email_field_tag :email, @user.email, required: true, class: 'form-control', id: 'floatingInput', placeholder: 'name@example.com' %>
      <label for="floatingInput">Почта</label>
    </div>
    <div class="form-floating">
      <%= text_field_tag :phone, @user.phone, required: true, class: 'form-control', id: 'floatingInput', placeholder: 'Телефон' %>
      <label for="floatingInput">Телефон</label>
    </div>
    <div class="form-floating">
      <%= password_field_tag :password, nil, required: true, class: 'form-control', id: 'floatingPassword', placeholder: 'Пароль' %>
      <label for="floatingPassword">Пароль</label>
    </div>
    <div class="form-floating">
      <%= password_field_tag :password_confirmation, nil, required: true, class: 'form-control', id: 'floatingPassword', placeholder: 'Підтвердіть пароль' %>
      <label for="floatingPassword">Підтвердіть пароль</label>
    </div>
    <%= submit_tag "Зареєструватися", class: 'w-100 btn btn-lg btn-primary' %>
    <br><br>
    <%= link_to "Повернутися", '/'%>
    <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2023</p>
  <% end %>
  <% if flash.now[:alert] %>
    <div class="alert alert-danger">
      <%= flash.now[:alert] %>
    </div>
  <% end %>
</div>