config/routes.rb
Rails.application.routes.draw do
  get 'product/new'
  get 'restaurants/new'
  get 'admin/index'
  get 'home/index'
  root 'home#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'cart', to: 'cart_items#index'

  get '/admin', to: 'admin#index'
  get '/admin/restaurants/new', to: 'restaurants#new'

  resources :users, only: [:create]
  resources :restaurants

  get 'restaurants/delete/:id', to: 'restaurants#destroy', as: 'restaurant_destroy'
  
  resources :restaurants do
    resources :products
  end

  resources :products, only: [:create, :destroy]

  resources :cart_items, only: [:create, :destroy] do
    patch :update_quantity, on: :member
  end

  resources :orders, only: [:create, :index]

  resources :orders do
    member do
      patch :mark_in_progress
      patch :mark_done
      patch :mark_canceled
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :user
  
  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products
  
  def total_price
    order_products.sum { |order_product| order_product.quantity * order_product.product.price }
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :restaurant
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
end

app/models/restaurant.rb
require 'mini_magick'

class Restaurant < ApplicationRecord
  has_many :products, dependent: :destroy
  has_one_attached :image

  after_save :crop_image

  def crop_image
    # return unless image.attached?
    # image.variant(resize_to_fill: [500, 350]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :phone, presence: true
  has_many :orders
  validates :email, uniqueness: true
  validates :phone, uniqueness: true
  
  def cart_items
    CartItem.where(user_id: id)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def index
    @restaurants = Restaurant.all
  end

  private

  def require_admin
    unless current_user && current_user.is_admin?
      flash[:danger] = 'У вас нет прав для просмотра этой страницы'
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.status = 'created'
    @order.date = Time.now

    @cart_items = current_user.cart_items
    @cart_items.each do |cart_item|
      @order.order_products.build(product_id: cart_item.product_id, quantity: cart_item.quantity)
    end

    puts '========'
    puts @order

    @order.save
    puts @order.errors.full_messages


    current_user.cart_items.destroy_all
    redirect_to root_path
  end

  def index
    @orders = Order.order(id: :desc)
  end

  def mark_in_progress
    @order = Order.find(params[:id])
    @order.update(status: "in_progress")
    redirect_to orders_path
  end

  def mark_done
    @order = Order.find(params[:id])
    @order.update(status: "done")
    redirect_to orders_path
  end

  def mark_canceled
    @order = Order.find(params[:id])
    @order.update(status: "canceled")
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user
  
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.build
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.build(product_params)
  
    if @product.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  
    if @product.update(product_params)
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: [:new, :create]

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:success] = "Ресторан успешно добавлен!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
  
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to root_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :description, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Неправильний емейл або пароль."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.password.blank?
      flash.now[:alert] = "Пароль не може бути порожнім."
      render :new
      return
    end

    if @user.password_confirmation.blank?
      flash.now[:alert] = "Пароль не може бути порожнім."
      render :new
      return
    end

    if @user.password_confirmation != @user.password
      flash.now[:alert] = "Паролі не співпадають."
      render :new
      return
    end

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      if @user.errors[:email].any? # Проверка ошибок валидации email
        flash.now[:alert] = "Реєстрацію за цією почтой вже здійснено."
      elsif @user.errors[:phone].any? # Проверка ошибок валидации phone
        flash.now[:alert] = "Реєстрацію за цим телефоном вже здійснено."
      else
        flash.now[:alert] = "Не вдалось зареєструватися."
      end
      render :new
    end
  end

  private

  def user_params
    params.permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/restaurants/edit.html.erb
<% content_for(:html_title) { 'Edit restaurant' } %>

<div class="container">
  <h2>Редагувати ресторан</h2>
  <%= link_to "Видалити ресторан", restaurant_destroy_path(@restaurant), method: :get, data: { confirm: 'Ви впевнені, що хочете видалити цей ресторан?' }, class: "btn btn-danger" %>
  <%= link_to "Додати продукт", new_restaurant_product_path(@restaurant), class: "btn btn-primary" %><br><br>
  <%= form_for(@restaurant) do |r| %>
    <div class="mb-3">
      <%= r.label 'Назва', class: 'form-label' %>
      <%= r.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= r.label 'Картинка' %>
      <%= r.file_field :image %>
    </div>
    
    <div class="mb-3">
      <%= r.label 'Адреса розташування', class: 'form-label' %>
      <%= r.text_field :address, class: 'form-control' %>
    </div>
  
    <div class="mb-3">
      <%= r.label 'Опис', class: 'form-label' %>
      <%= r.text_area :description, class: 'form-control' %>
    </div>
  
    <%= r.submit "Зберегти", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<% content_for(:html_title) { 'Додати ресторан' } %>

<div class="container">
  <h1>Додати новий ресторан</h1>
  <%= form_with(model: @restaurant, local: true) do |r| %>
    <div class="mb-3">
      <%= r.label 'Назва', class: 'form-label' %>
      <%= r.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= r.label 'Картинка' %>
      <%= r.file_field :image %>
    </div>
    
    <div class="mb-3">
      <%= r.label 'Адреса', class: 'form-label' %>
      <%= r.text_field :address, class: 'form-control' %>
    </div>
  
    <div class="mb-3">
      <%= r.label 'Опис', class: 'form-label' %>
      <%= r.text_area :description, class: 'form-control' %>
    </div>
  
    <%= r.submit "Зберегти", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<% content_for(:html_title) { @restaurant.name } %>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light"><%= @restaurant.name %></h1>
        <p class="lead text-body-secondary"><%= @restaurant.description %></p>
        <p>
          <a href="/" class="btn btn-primary">Повернутися</a>
        </p>
      </div>
    </div>
  </section>  

  <div class="products bg-body-tertiary">
    <div class="container">
      <h4>Товари</h4>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
        <% @restaurant.products.each do |product| %>
          <div class="col">
            <div class="card shadow-sm">
              <% if product.image.attached? %> 
                <%= image_tag product.image.variant(resize_to_fill: [500, 350]).processed, class: 'card-img-top' %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= product.name %></h5>
                <p class="card-text">₴ <%= product.price %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%= link_to 'Переглянути', restaurant_product_path(@restaurant, product), class: 'btn btn-sm btn-outline-primary' %>
                    <% if current_user.is_admin %>
                      <%= link_to 'Редагувати', edit_restaurant_product_path(@restaurant, product), class: 'btn btn-sm btn-primary' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>